name: Build and publish jpackage result to GitHub
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build and jpackage with Maven
      run: mvn -B package jpackage::jpackage@win --file pom.xml
    - name: Publish jpackage result
      uses: actions/upload-artifact@v2
      with:
        name: jpackage-result-windows
        path: target/release/SampleConverter-*.exe
