name: Build and publish to GitHub Packages
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build and jpackage with Maven
      run: mvn -B package jpackage::jpackage@win --file pom.xml
    - name: Publish package
      run: mvn -B deploy --file pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
